import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Hides Clerk's "development mode" badge via its `options`, not
            `layout` (that's what the type actually exposes it under). We're
            still on dev/test Clerk keys underneath (relaxed security, no
            custom domain) — this only removes the visual reminder. */}
        {/* Without these, Clerk doesn't know our app has its own sign-in/
            sign-up pages — the "Don't have an account?" link inside each
            widget falls back to Clerk's own hosted Account Portal page
            instead of our styled route, which is why the two pages could
            look consistent individually but navigating between them landed
            somewhere undesigned. */}
        <ClerkProvider
          signInUrl="/sign-in"
          signUpUrl="/sign-up"
          appearance={{ options: { unsafe_disableDevelopmentModeWarnings: true } }}
        >
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
