import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Hides Clerk's "development mode" badge via its `options`, not
            `layout` (that's what the type actually exposes it under). We're
            still on dev/test Clerk keys underneath (relaxed security, no
            custom domain) — this only removes the visual reminder. */}
        <ClerkProvider
          appearance={{ options: { unsafe_disableDevelopmentModeWarnings: true } }}
        >
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
