"""Request and response shapes for the conversations API.

The twin of `models/document.py`, and here for the same reason: these models pin
down what leaves the API, so a column added to `conversations` tomorrow does not
silently start appearing in the JSON the frontend reads.

One shape points inward rather than outward. `ConversationUpdate` is what a
rename is allowed to be, and its length cap is the same reflex as
`ChatRequest.message` — a title is a label in a sidebar, so a caller must not be
able to write a megabyte into my database through it.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field


class ConversationOut(BaseModel):
    """One row in the sidebar.

    `title` is nullable in the schema and therefore nullable here. In practice
    `_resolve_conversation` always writes one, and Day 9a's auto-titling
    replaces it with something shorter — but the database allows null, so the
    contract has to, and the frontend falls back to "New conversation".

    `updated_at` is the sort key, not `created_at`: the sidebar is ordered by
    recent *activity*, and `_save_exchange` touches this column after every
    exchange precisely so that ordering means something.
    """

    id: UUID
    title: str | None = None
    created_at: datetime
    updated_at: datetime


class MessageOut(BaseModel):
    """One bubble, replayed from the database.

    `sources` is deliberately loose. It is written by `rag.to_sources` and read
    by the `Source` interface in `apps/web/src/lib/types.ts`; re-declaring its
    nine fields a third time here would be a third place to keep in step, and
    the citation shape is documented where it is built. Same call
    `models/chat.py` already made for the streaming response.

    `model` is null on user rows — only an assistant message was generated by
    something.

    `run_id` is null on user rows for the same reason, and also on any answer
    written before migration 006 or produced while tracing was off. The browser
    uses it to let you rate an answer you have come back to; where it is null,
    the rating buttons simply do not appear.
    """

    id: UUID
    role: Literal["user", "assistant"]
    content: str
    model: str | None = None
    sources: list[dict] | None = None
    run_id: UUID | None = None
    created_at: datetime


class ConversationUpdate(BaseModel):
    """A rename. The only thing about a conversation a caller may change.

    Not `title: str | None` — a PATCH that omits the title is a request to do
    nothing, and answering it with a 200 would be a lie. Pydantic rejects the
    body before the handler runs.
    """

    title: str = Field(min_length=1, max_length=200)

    # In plain English: `Field(min_length=1, max_length=200)` makes Pydantic
    # check the length itself and return a 422 naming the problem, before any of
    # our code runs. So an empty title and a novel are both refused without ever
    # reaching the database.
